### ISSUE TITLE
Impressive

### ISSUE THREAD

**Issue by Helias** [carlospata/my-personal-diet#28]
Da due studenti del primo anno non mi aspettavo un progetto simile.

- avete scritto ottimi unit tests usando la parametrizzazione ed avete ignorato opportunamente con # pragma cover il codice che va puntualmente ignorato e non è di interesse per la code coverage
- avete usato i conventional commits, usato le branch e creato tantissime PR
- avete scritto una pipeline custom

Non avrei alcun appunto da fare anche perchè non mi aspetto tanta professionalità da studenti della triennale.

Bravissimi! 🚀 🥇 

Se vi siete divertiti e vi va di migliorare tecnicamente questo progetto al fine di imparare potreste:
- aggiungere un file requirements.txt con le dipendenze di "produzione" del progetto (es. tkinter)
- aggiungere un file requirements_dev.txt e mettere nella pipeline che pip installa le dipendenze di pytest da lì (vedi qd-starter-pack)
- aggiungere pylint nella pipeline e fixare tutte le migliorie che segnala il linter pylint (veri https://github.com/UNICT-Quality-Development/qd-starter-pack/pull/25 )

Una cosa che si impara solo col tempo e "masterando" il lingauggio di programmazione python è la qualità del codice, su quella avrei degli appunti da fare che saranno probabilmente simili anche a pylint, ma non mi aspetto da nessuno di scrivere codice di qualità (nemmeno da me stesso 😁 ).
Avete scritto tante funzioni con `if, elif` e dei `return`, in realtà quando in un if è scritto un return si può scrivere direttamente `if` al posto di `elif` per migliorare leggibilità e forse un po' di efficienza nel codice, inoltre, nella funzione `basal_metabolism(`è presente una variabile res che si potrebbe omettere, al posto dell'assegnazione `res =`è possibile mettere direttamente `return ...` in modo da risparmiare una variabile e quindi della memoria.

Comunque, tutte queste ottimizzazioni si possono fare automaticamente usando pylint come linter, il vostro progetto mi è piaciuto tantissimo, ma sappiate che si può sempre imparare e migliorare.

⭐ ⭐ ⭐ ⭐ ⭐  🚀

**Comment by carlospata** [comment]
Ciao @Helias, ho provato a inserire tutto quello che hai scritto tra cui pylint, di cui il test falliva anche perchè ad esempio mi segnalava come errore la riga vuota, ma personalmente la uso per un fatto di leggibilità. 
Comunque uno dei problemi che ho riscontrato è stata la comunicazione tra i vari file e le varie classi che spesso davano errore -> "Circular Import" (ex: class1 importa class2 che a sua volta importa class1).
Volevo capire se c'è un modo pulito per risolvere questo problema oppure in questo caso è sbagliata la progettazione del codice.

**Comment by Helias** [comment]
è possibile che sia sbagliata la progettazione del codice, comunque se alcuni warning/errori di pylint vi sembrano superflui potete "ignorarli" o "disabilitarli" nel file .pylintrc, comunque per me il progetto è finito nei prossimi giorni generemo gli attestati firmati e li invierò via email
le migliorie sono opzionali, a vostra discrezione

**Comment by carlospata** [comment]
Va benissimo, grazie 👍
